variable "vpccidr"{}
variable "vpcname"{}
variable "pubsub1"{}
variable "pubsub2"{}
variable "pubsubaz1"{}
variable "pubsubaz2"{}
variable "pubsubname1"{}
variable "pubsubname2"{}
variable "igwname"{}
variable "igwcidr"{}
variable "block1"{}
variable "block2"{}
variable "block3"{}
variable "env"{}
variable "sgname"{}
variable "clustername"{}
